### ISSUE TITLE
MainActivity changeLoadState没有执行

### ISSUE THREAD

**Issue by BigBigDeBoy** [sange93/MVVMDemo#1]
现在想统一加上dialog加载中，结束消失，怎么做

**Comment by BigBigDeBoy** [comment]
loadState.value = LoadState.Loading()
   loadState.value 是null

**Comment by sange93** [comment]
源码中的扩展属性loadState这里确实有问题，观察者没有执行。建议将loadState字段定义在一个BaseViewModel基类中，使用时VM类继承BaseViewModel，这样loadState字段观察者回调就会被执行了。源码已更新，可以看下MainActivityVM.kt。感谢提出！

**Comment by BigBigDeBoy** [comment]
我现在就是放在baseviewemodel定义的了，不知道为什么扩展方法不行

**Comment by sange93** [comment]
扩展属性并没有真的给类增加属性，只是通过get set方法计算属性的值。  
val ViewModel.loadState: MutableLiveData<LoadState>
    get() = MutableLiveData()
这里的get方法  每次调用都得到的是个新对象，不是同一个对象，所以对loadState的观察者是不起作用的。

**Comment by BigBigDeBoy** [comment]
对 懂了 thx
